
CREATE TABLE JOB (
   NAME               VARCHAR2(50 CHAR),
   IMPLEMENTATION     VARCHAR2(255 CHAR),
   CRON_EXPRESSION    VARCHAR2(50 CHAR),
   NEXT_RUN           DATE,
   PARAMS             VARCHAR2(4000 CHAR),
   RUNNING            NUMBER(1, 0) DEFAULT 0 NOT NULL,
   SUSPENDED          NUMBER(1, 0) DEFAULT 0 NOT NULL,
   DISABLED           NUMBER(1, 0) DEFAULT 0 NOT NULL,
   "SCHEDULE"         VARCHAR2(255 CHAR),
   RUN_QUEUE          VARCHAR2(255 CHAR),
   LAST_EXECUTION_ID  NUMBER,
   ERROR_MAIL_ADDRESS VARCHAR2(255 CHAR),
   PRIMARY KEY (NAME)
);

CREATE TABLE JOB_EXECUTION (
   ID         NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
   JOB_NAME   VARCHAR2(50 CHAR) NOT NULL,
   STATUS     VARCHAR2(20 CHAR),
   START_TIME TIMESTAMP(6),
   END_TIME   TIMESTAMP(6),
   MESSAGE    VARCHAR2(4000 CHAR),
   NODE_NAME  VARCHAR2(255 CHAR),
   SIGN_OF_LIFE_TIME TIMESTAMP(6),
   PRIMARY KEY (ID)
);

alter table JOB add
   constraint FK_JOB_LAST_EXECUTION
      foreign key (LAST_EXECUTION_ID) references job_execution on delete set null;

alter table JOB_EXECUTION add
   constraint FK_EXECUTION_JOB
      foreign key (JOB_NAME) references job on delete cascade;


/* Granting rights to other application user:

GRANT SELECT,INSERT,UPDATE,DELETE ON JOB TO someuser;
GRANT SELECT,INSERT,UPDATE,DELETE ON JOB_EXECUTION TO someuser;

 */
